import type { Metadata } from "next";
import { Syne, Cormorant_Garamond, Archivo } from "next/font/google"; // Import Archivo font
import Header from '@/components/Header'; // Import Header component
import SmoothScroll from '@/components/SmoothScroll'; // Import SmoothScroll component

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne", // Define CSS variable for Syne
  display: "swap",
});

const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant-garamond", // Define CSS variable for Cormorant Garamond
  weight: ["300", "400", "500", "600", "700"], // Specify weights if needed
  display: "swap",
});

const archivo = Archivo({ // Define Archivo font
  subsets: ["latin"],
  variable: "--font-archivo",
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'tr' }];
}

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <div
      className={`${syne.variable} ${cormorantGaramond.variable} ${archivo.variable}`} // Apply font variables including Archivo
    >
      <Header locale={locale} />
      <SmoothScroll>
        {children}
      </SmoothScroll>
    </div>
  );
}
